Title: Aldo Reyes BI Portfolio
logo: assets/images/Logo Github Photo.png
description: "Modular, scalable documentation for BI projects"
baseurl: ""
url: "https://aldoreyes84.github.io"
default_lang: en

plugins:
  - jekyll-seo-tag


collections:
  pages:
    output: true
    permalink: /:lang/:name/





flyer_url: "/assets/files/Portfolio Flyer.pdf"

# Navigation labels
nav:
  home: "Home"
  experience: "Working Experience"
  about: "About Me"
  dashboards: "Power BI Dashboards"
  contact: "Contact"
  share: "Share"

# Social links
social:
  github: "https://github.com/AldoReyes84"
  linkedin: "https://linkedin.com/in/aldoreyes84"
  email: "mailto:aldoreyes.bi@gmail.com"

sections:
  contoso:
    name: "Contoso Sales Dashboard"
    url: "https://aldoreyes84.github.io/contoso_pbi_dashboard"
  adventureworks:
    name: "AdventureWorks2022 Analysis"
    url: "https://aldoreyes84.github.io/adworks_data_analysis"
  ssis:
    name: "SSIS Integration with Python Faker"
    url: "https://aldoreyes84.github.io/etl_ssis_integration_package"
  experience:
    name: "Working Experience"
    url: "https://aldoreyes84.github.io/working_experience"
  aboutme:
    name: "About me"
    url: "https://aldoreyes84.github.io/about_me"  
  portfolio:
    name: "Portfolio"
    url: "https://aldoreyes84.github.io/AldoReyes.github.io/"



