Title: Aldo Reyes BI Portfolio
logo: assets/images/Logo Github Photo.png
description: "Modular, scalable documentation for BI projects"
url: "https://aldoreyes84.github.io"

theme: jekyll-theme-minimal

flyer_url: "/assets/files/Portfolio Flyer.pdf"

# Navigation labels
nav:
  home: "Home"
  experience: "Working Experience"
  about: "About Me"
  dashboards: "Power BI Dashboards"
  contact: "Contact"
  share: "Share"

# Social links
social:
  github: "https://github.com/AldoReyes84"
  linkedin: "https://linkedin.com/in/aldoreyes84"
  email: "mailto:aldoreyes.bi@gmail.com"

sections:
  contoso:
    name: "Contoso Sales Dashboard"
    url: "https://aldoreyes84.github.io/Contoso-Sales-Power-BI-Dashboard/"
  adventureworks:
    name: "AdventureWorks2022 Analysis"
    url: "https://aldoreyes84.github.io/SQL_Server_AdventureWorks/"
  ssis:
    name: "SSIS Integration with Python Faker"
    url: "https://aldoreyes84.github.io/ETL/"
  experience:
    name: "Working Experience"
    url: "https://aldoreyes84.github.io/Working-Experience/"
  aboutme:
    name: "About me"
    url: "https://aldoreyes84.github.io/About-me/"  
  portfolio:
    name: "Portfolio"
    url: "https://aldoreyes84.github.io/AldoReyes.github.io/"

es:
  main_header: "Encabezado principal del sitio"
  home: "Inicio"
  home_icon: "Icono de inicio"
  open_main_menu: "Abrir menú principal"
  main_navigation: "Navegación principal"
  open_panel: "Abrir panel de"
  go_to_section: "Ir a la sección de"
  dropdown_icon: "Icono de desplegable"
  share_menu: "Menú de compartir"
  share_icon: "Icono de compartir"
  skills: "Habilidades"
  tools: "Herramientas"
  work_experience: "Experiencia laboral"
  about_me: "Sobre mí"
  projects: "Proyectos"
  documents: "Documentos"
  contact: "Contacto"
  share: "Compartir"

en:
  main_header: "Main site header"
  home: "Home"
  home_icon: "Home icon"
  open_main_menu: "Open main menu"
  main_navigation: "Main navigation"
  open_panel: "Open"
  go_to_section: "Go to"
  dropdown_icon: "Dropdown icon"
  share_menu: "Share menu"
  share_icon: "Share icon"
  skills: "Skills"
  tools: "Tools"
  work_experience: "Work Experience"
  about_me: "About me"
  projects: "Projects"
  documents: "Documents"
  contact: "Contact"
  share: "Share"

